### ISSUE TITLE
White image file not found. Revise calibration path settings. 0.9.3

### ISSUE THREAD

**Issue by pithydon** [hahnec/plenopticam#32] opened 2022-09-25 21:02 UTC
It seams this is a reacquiring problem. I get this error with version 0.9.3.

**Comment by pithydon** [comment] 2022-09-26 15:36
The tar file and photos are from the same camera. I've only tried 0.9.3. My camera creates a .LFP and .LFR. I tried to decode both files. I installed plenopticam through pip.

**Comment by hahnec** [comment] 2022-09-28 09:33
Were there any errors/warnings during installation via pip? You can try prior releases with:

>  pip install plenopticam==0.9.2

If it is not working with earlier versions, I can try to find the cause for this by reverse-engineering using the metadata from your photographs. Please upload them together with the corresponding tar archive and send the link, so I can reproduce the issue on my side.

**Comment by pithydon** [comment] 2022-09-29 15:16
Doesn't work with 0.9.2 either. Didn't see any install errors. Here are the files... https://drive.google.com/drive/folders/1VQf5RzF69a4q4D4RDa6tz1UZgAe7_dE5?usp=sharing

**Comment by hahnec** [comment] 2022-10-05 18:00
Hi again!

Thanks for sharing your files. I managed to free some time to analyze the problem and it turns out that the JSON data in your LFP does match the white image calibration files in the tar-archive. 

I have attached the JSON data below as a zip file extracted from your LPF file. There you will find two sha1 values that do not match any in your provided tar-archive (cal_file_manifest.json). The sha1 value at "derivationArray" has previously shown to help identifying the white image calibration file for other Lytro cameras. It doesn't work for yours tho? This usually means that tar-archive and LFP file are not taken from the same Lytro camera.

Note that I have never been affiliated with Lytro and the white image calibration matching is based on reverse-engineering from open-source repos, similar bug reports and thus somewhere between blind and educated guesses. 

As the important sha1 information is not provided in your LFP file, I doubt I can do much on the coding side.

Can you re-export your LFP file in an attempt to include more metadata? When extracting JSON data from LFP files, keep an eye on "geometryCorrectionRef" or "derivationArray" and see if they are part of the cal_file_manifest.json in your tar-archive.

[IMG_0167.zip](https://github.com/hahnec/plenopticam/files/9717913/IMG_0167.zip)

**Comment by pithydon** [comment] 2022-10-11 04:23
I found a setting to save files as raw instead of xraw on my camera. I got to a different error. TypeError: __str__ returned non-string (type Image)

**Comment by hahnec** [comment] 2022-10-16 16:40
You can attach the file and give me a chance to debug again. As my time is limited, it might take me some time.

Have you checked whether a JSON file has been exported from your new file? Could you identify one of the above-mentioned entries and match them to those in the cal_file_manifest.json from your tar-archive?

**Comment by pithydon** [comment] 2022-10-20 20:44
I did manage to get thumbnails out this time with the new file set to raw instead of xraw.
https://drive.google.com/file/d/1ma7aQUVF2ePHksCS88m6e7Nqr1uMXfu6/view?usp=sharing
https://drive.google.com/file/d/1xzGPzN7N2CUy8AA9oP0LcHiXYtU4Pz_T/view?usp=sharing

**Comment by pithydon** [comment] 2022-10-20 21:29
Not entirely sure what the question is but I found the sha1 for "geometryCorrectionRef" but not the one for "derivationArray" in cal_file_manifest.json. "geometryCorrectionRef" was in the backup folder plenopticam created.

**Comment by hahnec** [comment] 2022-11-05 13:29
I passed the files to v0.9.3 on my side and can confirm that they run through without issues. In conclusion, the original problem seem to be linked to metadata file extraction? I am closing as this appears to be resolved.

**Closed by hahnec** 2022-11-05 13:29 UTC
Labels: invalid
